name: Keep Alive

on:
  schedule:
    - cron: '0,30 * * * *' 
  workflow_dispatch:         # manual trigger too

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend
        run: |
          curl -f https://auto-mobile-spare-parts.onrender.com/health
          echo "Server pinged successfully"
